#!/bin/sh
# Read the CLIProxy API key from the Docker Swarm secret mount and write it
# into config.yaml at container startup.  Using a secret mount instead of
# environment variables or bind-mounted files means the key is never visible
# in `docker inspect`, `docker history`, or any image layer.
# Mirrors the pattern used in goosed-entrypoint.sh for goose_secret_key.

set -e

CONFIG_FILE="/CLIProxyAPI/config.yaml"
SECRET_FILE="/run/secrets/cliproxy_api_key"

API_KEY=""
if [ -f "${SECRET_FILE}" ]; then
    API_KEY=$(cat "${SECRET_FILE}")
fi

# Write config.yaml at runtime so the API key is never baked into the image.
cat > "${CONFIG_FILE}" <<EOF
# CLIProxyAPI runtime configuration — generated by cliproxy-entrypoint.sh
# The api-keys value is injected from the Docker Swarm secret cliproxy_api_key.

host: "127.0.0.1"
port: 8317

remote-management:
  allow-remote: false
  secret-key: ""
  disable-control-panel: true

auth-dir: "/root/.cli-proxy-api"

api-keys:
  - "${API_KEY}"

debug: false
pprof:
  enable: false

logging-to-file: false
usage-statistics-enabled: false
EOF

exec /CLIProxyAPI/CLIProxyAPI "$@"
